
pm uninstall --user 0 com.samsung.android.arzone
pm uninstall --user 0 com.samsung.android.ardrawing
pm uninstall --user 0 com.samsung.android.visionarapps
pm uninstall --user 0 com.samsung.android.bixby.agent
pm uninstall --user 0 com.samsung.android.visionintelligence
pm uninstall --user 0 com.samsung.android.bixby.agent.dummy
pm uninstall --user 0 com.samsung.android.bixbyvision.framework
pm uninstall --user 0 com.android.bookmarkprovider
pm uninstall --user 0 flipboard.boxer.app
pm uninstall --user 0 com.android.chrome
pm uninstall --user 0 com.samsung.android.livestickers
pm uninstall --user 0 com.google.android.apps.turbo
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.facebook.katana
pm uninstall --user 0 com.facebook.system
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.facebook.services
pm uninstall --user 0 com.samsung.android.themestore
pm uninstall --user 0 com.samsung.android.app.watchmanager
pm uninstall --user 0 com.samsung.android.game.gametools
pm uninstall --user 0 com.samsung.android.game.gamehome
pm uninstall --user 0 com.samsung.android.game.gos
pm uninstall --user 0 com.google.android.gm
pm uninstall --user 0 com.google.android.googlequicksearchbox
pm uninstall --user 0 com.google.ar.core
pm uninstall --user 0 com.google.android.videos
pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
pm uninstall --user 0 com.google.android.apps.photos
pm uninstall --user 0 com.sec.android.service.health
pm uninstall --user 0 com.samsung.android.app.simplesharing
pm uninstall --user 0 com.microsoft.office.officehubrow
pm uninstall --user 0 com.microsoft.skydrive
pm uninstall --user 0 com.microsoft.office.outlook
pm uninstall --user 0 com.samsung.android.privateshare
pm uninstall --user 0 com.samsung.android.app.spage
pm uninstall --user 0 com.sec.android.desktopmode.uiservice
pm uninstall --user 0 com.samsung.android.mateagent
pm uninstall --user 0 com.samsung.sree
pm uninstall --user 0 com.sec.android.app.shealth
pm uninstall --user 0 com.sec.android.app.sbrowser
pm uninstall --user 0 com.sec.android.app.kidshome
pm uninstall --user 0 com.samsung.android.app.notes
pm uninstall --user 0 com.samsung.android.authfw
pm uninstall --user 0 com.samsung.android.samsungpass
pm uninstall --user 0 com.samsung.android.spay
pm uninstall --user 0 com.samsung.knox.securefolder
pm uninstall --user 0 com.samsung.android.beaconmanager
pm uninstall --user 0 com.samsung.android.oneconnect
pm uninstall --user 0 com.rsupport.rs.activity.rsupport.aas2
pm uninstall --user 0 com.touchtype.swiftkey
pm uninstall --user 0 com.swiftkey.swiftkeyconfigurator
pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
pm uninstall --user 0 com.google.android.youtube
pm uninstall --user 0 com.google.android.apps.youtube.music
pm uninstall --user 0 com.samsung.android.samsungpassautofill
pm uninstall --user 0 com.samsung.android.bixby.wakeup
pm uninstall --user 0 com.google.android.apps.docs
pm uninstall --user 0 com.microsoft.appmanager
pm uninstall --user 0 com.sec.android.app.voicenote
pm uninstall --user 0 com.google.android.apps.maps
pm uninstall --user 0 com.android.wallpaper.livepicker
pm uninstall --user 0 com.touchtype.swiftkey
pm uninstall --user 0 com.samsung.android.honeyboard
pm uninstall --user 0 com.samsung.android.service.peoplestripe
pm uninstall --user 0 com.sec.android.daemonapp
pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe
pm uninstall --user 0 com.samsung.android.aremojieditor
pm uninstall --user 0 com.sec.android.widgetapp.webmanual
pm uninstall --user 0 com.android.stk
pm uninstall --user 0 com.samsung.android.bixby.service
pm uninstall --user 0 com.samsung.android.app.tips
pm uninstall --user 0 com.sec.android.mimage.avatarstickers
pm uninstall --user 0 com.samsung.android.app.routines
pm uninstall --user 0 com.samsung.android.kidsinstaller
